# Generated by Django 5.1.4 on 2025-01-01 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('template_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='templates/images')),
                ('file', models.FileField(upload_to='templates/files')),
                ('is_public', models.BooleanField(blank=True, default=False)),
                ('usage', models.PositiveIntegerField(blank=True, default=0)),
                ('is_active', models.BooleanField(blank=True, default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
