# Generated by Django 5.1.4 on 2025-01-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_proxyuser_userprofile_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProxyUser',
        ),
    ]
