# Generated by Django 5.1.4 on 2025-01-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_proxyuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='file',
            field=models.FileField(blank=True, upload_to='templates/files'),
        ),
    ]
