# Generated by Django 5.1.4 on 2025-01-29 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_template_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_owner', to='app.userprofile'),
        ),
    ]
